SELECT *
FROM DS_SALARIES;--MY ALL DATA: 3755  Rows

---DESCRIBE DS_SALARIES TABLE 
DESCRIBE DS_SALARIES;
/*
Name               Null? Type          
------------------ ----- ------------- 
WORK_YEAR                NUMBER(38)    
EXPERIENCE_LEVEL         VARCHAR2(26)  
EMPLOYMENT_TYPE          VARCHAR2(26)  
JOB_TITLE                VARCHAR2(128) 
SALARY                   NUMBER(38)    
SALARY_CURRENCY          VARCHAR2(26)  
SALARY_IN_USD            NUMBER(38)    
EMPLOYEE_RESIDENCE       VARCHAR2(26)  
REMOTE_RATIO             NUMBER(38)    
COMPANY_LOCATION         VARCHAR2(26)  
COMPANY_SIZE             VARCHAR2(26)  
*/



--NULL VALUES CONTROL
SELECT  t.column_name
FROM    user_tab_columns t
WHERE   t.nullable = 'Y'
        AND t.table_name = 'DS_SALARIES'
        AND t.num_distinct = 0;---THERE IS NO NULL VALUE
        
---EXPERIENCE_LEVEL CONTROL
SELECT EXPERIENCE_LEVEL, 
FROM (SELECT EXPERIENCE_LEVEL, ROW_NUMBER() OVER (PARTITION BY EXPERIENCE_LEVEL ORDER BY EXPERIENCE_LEVEL) AS LEVEL_NUMBER, 
ROW_NUMBER() OVER (ORDER BY EXPERIENCE_LEVEL) AS TOTAL_NUMBER
FROM DS_SALARIES)
        
