SELECT * 
FROM DEV_IMDB;---OUR FIRST TABLE. WE DON'T NEED Poster_Link COLUMN. SO I DIDIN'T IMPORT IT.

DESCRIBE DEV_IMDB;-- GROSS TYPE IS VARCHAR. I SHOULD CHANGE THIS COLUMN WITH TO_NUMBER DATA TYPE 

ALTER TABLE DEV_IMDB
    RENAME COLUMN SERIES_TITLE TO MOVIES_TITLE;---WE CHANGED THE COLUMN NAME FROM SERIES_TITLE TO MOVIES_TITLE 


SELECT COUNT(*)
FROM DEV_IMDB 
WHERE GROSS IS NULL;--THERE ARE 169 ROWS NULL VALUES IN GROSS COLUMN

CREATE TABLE DEV_IMDB_V2 AS 
SELECT MOVIES_TITLE,          
RELEASED_YEAR,           
CERTIFICATE,           
RUNTIME,               
GENRE,                
IMDB_RATING,            
OVERVIEW,            
META_SCORE,              
DIRECTOR,              
STAR1,                 
STAR2,                
STAR3,             
STAR4,                
NO_OF_VOTES,            
TO_NUMBER(REPLACE(GROSS, ',', '')) AS GROSS
FROM DEV_IMDB 
WHERE GROSS IS NOT NULL;---I REMOVED NULL VALUES AND CHANGE THE GROSS COLUMN FROM CHAR TO NUMBER NOW, WE CAN DESCRIBE TABLE AND SEE THE CHANGING

DESCRIBE DEV_IMDB_V2;
               
SELECT *
FROM DEV_IMDB_V2;

SELECT count(*) 
FROM DEV_IMDB_V2;--831 ROWS

SELECT 
    MIN(RELEASED_YEAR), 
    MAX(RELEASED_YEAR) 
FROM DEV_IMDB; --OUR DATA IS BETWEEN 1920 AND 2020 YEARS.

SELECT RELEASED_YEAR, COUNT(*)
FROM DEV_IMDB_V2 
GROUP BY RELEASED_YEAR
ORDER BY COUNT(*) DESC;-- 2014 was the year when most films were releaed.



SELECT * 
FROM 
    (SELECT A.*, ROW_NUMBER() OVER(ORDER BY GROSS DESC) SEQ 
    FROM DEV_IMDB_V2 A
    WHERE GROSS IS NOT NULL) A
WHERE A.SEQ=1; --YOU CAN FIND MAX GROSS FILM INFORMATIONS WITH ANOTHER EASY WAY BUT I REALLY LIKE TO USE ROW_NUMBER FUNCTION :)
               --WITH THIS QUERY "BRAZIL" IS THE MOST GROSS(9,929,135) FILM.



SELECT * 
FROM 
    (SELECT A.*, ROW_NUMBER() OVER(ORDER BY IMDB_RATING DESC) SEQ 
    FROM DEV_IMDB_V2 A
    ) A
WHERE A.SEQ=1; --AS YOU EXPECT, The Shawshank Redemption IS THE HIGHEST IMDB_RATING MOVIE (93). 


SELECT DIRECTOR, COUNT(*)
FROM DEV_IMDB_V2

GROUP BY DIRECTOR
ORDER BY COUNT(*) DESC 
FETCH FIRST 5 ROWS ONLY; ---MOSTLY OCCURED DIRECTORS 
/*
Steven Spielberg
Martin Scorsese
Alfred Hitchcock
Woody Allen
Quentin Tarantino
*/
SELECT *
FROM (
        SELECT V2.*, ROW_NUMBER() OVER (ORDER BY TO_NUMBER(REPLACE(RUNTIME, 'min')) DESC) AS SEQ
        FROM DEV_IMDB_V2 V2
     ) 
WHERE SEQ=1; --HAMLET IS THE LONGEST FILM BETWEEN 1920 AND 2020 YEARS.DIRECTOR Kenneth Branagh AND GROSS IS 4.414.535.