SELECT * 
FROM DEV_IMDB;---OUR FIRST TABLE. WE DON'T NEED Poster_Link COLUMN. SO I DIDIN'T IMPORT IT.

SELECT count(*) 
FROM DEV_IMDB;--1000 data

SELECT 
    MIN(RELEASED_YEAR), 
    MAX(RELEASED_YEAR) 
FROM DEV_IMDB; --OUR DATA IS BETWEEN 1920 AND 2020 YEARS.

SELECT RELEASED_YEAR, COUNT(*)
FROM DEV_IMDB 
GROUP BY RELEASED_YEAR
ORDER BY COUNT(*) DESC;-- 2014 was the year when most films were releaed.


SELECT *
FROM DEV_IMDB 
ORDER BY GROSS DESC;--THERE ARE 169 ROWS NULL VALUES IN GROSS COLUMN

SELECT * 
FROM 
    (SELECT A.*, ROW_NUMBER() OVER(ORDER BY GROSS DESC) SEQ 
    FROM DEV_IMDB A
    WHERE GROSS IS NOT NULL) A
WHERE A.SEQ=1; --YOU CAN FIND MAX GROSS FILM INFORMATIONS WITH ANOTHER EASY WAY BUT I REALLY LIKE TO USE ROW_NUMBER FUNCTION :)
               --WITH THIS QUERY "BRAZIL" IS THE MOST GROSS(9,929,135) FILM.




